version: "3.5"
networks:
  facebook:
    driver: ${NETWORKS_DRIVER}
    # driver_opts:
    #   encrypted: "1"
volumes:
  facebook:
    driver: ${VOLUMES_DRIVER}
  portainer:
    driver: ${VOLUMES_DRIVER}
  cadvisor:
    driver: ${VOLUMES_DRIVER}
services:
  facebook:
    build:
      context: ./facebook
    volumes:
      - facebook:/var/log
      - ${FACEBOOK_APP_PATH}:/app
    ports:
      - "${FACEBOOK_SUPERUSER_PORT}:9001"
      - "${FACEBOOK_APP_PORT}:5000"
    networks:
      - facebook
  portainer:
    image: portainer/portainer:latest
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - facebook
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "${CADVISOR_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - facebook
